#!/usr/bin/env bash 
#fizbuzz
number=1
while [ $number -le 100 ]; do
if [ $((number%15)) = 0 ];
then
echo "Fizzbuzz";
elif [ $((number%5)) = 0];
then 
echo "Buzz";
elif [ $((number%5)) = 0 ];
then
echo "Fizz";
else
echo "$number";
fi;
    number=$(( number + 1 ));
done
