#!/usr/bin/env bash
# informations about a file.

FILE="holbertonschool"

if [ -e "$FILE" ]
then 
echo "holbertonschool file exists"

else echo "holbertonschool file not empty"
fi
if [ -f "$FILE" ]
then 
echo "holbertonschool is regular file"
fi 
else 
echo "holbetonschool file does not exist"
fi
